vich_uploader:
  db_driver: orm
  mappings:
    blog_image:
      namer: vich_uploader.namer_origname
      uri_prefix: "%app.blogs_images_url%"
      upload_destination: "%app.blogs_images%"
      inject_on_load: false
      delete_on_update: false
      delete_on_remove: false

  metadata:
    type: attribute
